name: "ci"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-editorconfig-checker:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5.0.0"
      - uses: "editorconfig-checker/action-editorconfig-checker@main"
      - run: "editorconfig-checker"

  ci:
    runs-on: "ubuntu-latest"
    container: "theoludwig/gcc-make-doxygen-ubuntu:latest"

    strategy:
      matrix:
        task:
          [
            01-syscalls-fs-1-copy,
            01-syscalls-fs-2-reverse,
            01-syscalls-fs-3-ls,
            02-syscalls-process-1-fork,
            02-syscalls-process-2-redirect,
            02-syscalls-process-3-redirect-pipe,
            03-thread-1-sort,
            projet-ctar,
          ]

    steps:
      - uses: "actions/checkout@v5.0.0"

      - run: "make"
        working-directory: ${{ matrix.task }}

      - run: "make lint"
        working-directory: ${{ matrix.task }}

      - run: "make clean"
        working-directory: ${{ matrix.task }}
